### ISSUE TITLE
Extension does not connect to game

### ISSUE THREAD

**Issue by SuperTails** [hugeBlack/McfDebugger_Extension#4]
I have installed the mod (v1.1.1) and the extension (v0.1.1) in Minecraft 1.16.5. I checked the websocket with a python script and verified that the mod was sending data, so I know that the mod is installed correctly.

Here's the steps I tried:

1. I installed the extension
2. I created a `launch.json`
3. I opened a datapack folder in VSCode
4. I opened a Minecraft world containing that datapack
5. I clicked "start debugging" and ran some functions

However, the debugger did not seem to ever connect to the game (did not trigger breakpoints, show exceptions, print info, etc).

**Comment by hugeBlack** [comment]
Sorry for being late. Does the path of your datapack contain Chinese, Japanese characters or something like that? I have tested and found that these characters would be URI encoded when the extension was trying to read the path.
If so, please try removing these characters and start debugger again, I'll fix this issue in next release.

**Comment by hugeBlack** [comment]
Since you didn't reply,  this issue may be solved, so I close this issue.

**Comment by hanmindev** [comment]
Hey, I'm getting the same issue. I have the debugger (1.2.1) and the extension (0.2.1) and the debugger doesn't seem to connect to the game.  
Here's the steps I tried:
1. I installed the extension
2. I tried both adding a ```launch.json``` and adding "launch" to my workplace.
3. I opened a Minecraft world with that datapack
4. I clicked "start debugging"
5. The debugger starts, but immediately ends. The function I am running does have breakpoints.

I know the mod is correctly installed because I can see the ```/mcfDebuggerConfig ``` command in-game.
I am using the default launch.json

My datapack path does not contain any strange characters, other than spaces. I have tried this without spaces and it still does not work.
